create database customer_shopping;
use customer_shopping;
create table customer (
customer_id int primary key ,
age int,
gender varchar(10) ,
item_purchased varchar(50), 
category varchar(50),
purchase_amount int,
location varchar(50),
size varchar(3),
color varchar(50),
season varchar(50),
review_rating float,
subscription_status varchar(5),
shipping_type varchar(50),
discount_applied varchar(5),
promo_code_used varchar(5),
previous_purchases int,
payment_method varchar(50), 
frequency_of_purchases varchar(50)
);
select*from customer;


-- Q1. What is the total revenue generated by male vs female customers ?

select gender,sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2 Which customer used a discount but still spent more than the average purchase_amount ?

select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount)from customer);

-- Q3 Which are the top 5 products with the highest average review rating ?

select item_purchased, round(avg(review_rating),2) as 'Average Product Rating'
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4 Compare the avg purchase amount between standard and express shipping ?

select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5 Do subscribed customer spend more ? Compare avg spend and total revenue between subscribe and non-subscriber.

select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc ;

-- Q6 Which 5 products have the highest percentage of purchases with discount applied ?

select item_purchased,
round(100*  sum(case when discount_applied = 'Yes' Then 1 else 0 end)/count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;
